# Generated by Django 6.0 on 2025-12-30 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('plan_type', models.CharField(choices=[('personal', 'Personal'), ('ai_recommended', 'AI Recommended')], default='personal', max_length=20)),
                ('ai_prompt', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'travel_plans',
            },
        ),
        migrations.CreateModel(
            name='PlanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_details', to='places.place')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='plans.travelplan')),
            ],
            options={
                'db_table': 'plan_details',
                'ordering': ['date', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='AIQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_questions', to='plans.travelplan')),
            ],
            options={
                'db_table': 'ai_questions',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='TravelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=500, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='plans.travelplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'travel_posts',
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='plans.travelpost')),
            ],
            options={
                'db_table': 'post_likes',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='plans.travelpost')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='PlanDetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plans.plandetail')),
            ],
            options={
                'db_table': 'plan_detail_images',
                'ordering': ['order_index'],
                'indexes': [models.Index(fields=['detail'], name='plan_detail_detail__7ee8ba_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='travelplan',
            index=models.Index(fields=['user'], name='travel_plan_user_id_b0bc4a_idx'),
        ),
        migrations.AddIndex(
            model_name='travelplan',
            index=models.Index(fields=['created_at'], name='travel_plan_created_5a109e_idx'),
        ),
        migrations.AddIndex(
            model_name='travelplan',
            index=models.Index(fields=['is_public'], name='travel_plan_is_publ_464b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='plandetail',
            index=models.Index(fields=['plan'], name='plan_detail_plan_id_7b4781_idx'),
        ),
        migrations.AddIndex(
            model_name='plandetail',
            index=models.Index(fields=['date'], name='plan_detail_date_ac2446_idx'),
        ),
        migrations.AddIndex(
            model_name='aiquestion',
            index=models.Index(fields=['plan'], name='ai_question_plan_id_2187f6_idx'),
        ),
        migrations.AddIndex(
            model_name='travelpost',
            index=models.Index(fields=['user'], name='travel_post_user_id_4defaa_idx'),
        ),
        migrations.AddIndex(
            model_name='travelpost',
            index=models.Index(fields=['created_at'], name='travel_post_created_d8ddb5_idx'),
        ),
        migrations.AddIndex(
            model_name='travelpost',
            index=models.Index(fields=['like_count'], name='travel_post_like_co_d07035_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['post'], name='post_likes_post_id_c6421f_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['user'], name='post_likes_user_id_7d46ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('post', 'user')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post'], name='comments_post_id_7ee550_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='comments_user_id_8613ff_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='comments_created_d5740c_idx'),
        ),
    ]
