# Generated by Django 6.0 on 2026-01-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plandetailimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='plandetailimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='plan_images/'),
        ),
    ]
