# Generated by Django 5.2.6 on 2026-01-09 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_remove_plandetailimage_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('gapyeong_yangpyeong', '가평/양평'), ('gangneung_sokcho', '강릉/속초'), ('gyeongju', '경주'), ('busan', '부산'), ('yeosu', '여수'), ('incheon', '인천'), ('jeonju', '전주'), ('jeju', '제주'), ('chuncheon_hongcheon', '춘천/홍천'), ('taean', '태안')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('travel_style', models.CharField(choices=[('healing', '힐링/휴양'), ('activity', '액티비티'), ('culture', '문화/역사'), ('food', '맛집 투어'), ('nature', '자연 경관')], max_length=20)),
                ('companions', models.IntegerField(default=1)),
                ('additional_request', models.TextField(blank=True)),
                ('ai_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to='plans.travelplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_travel_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_travel_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_travel_r_user_id_c7dd84_idx'), models.Index(fields=['status'], name='ai_travel_r_status_958601_idx')],
            },
        ),
    ]
