# Generated by Django 6.0 on 2026-01-20 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_aitravelrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plan_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'plan_likes',
            },
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_post_id_7ee550_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_user_id_8613ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_created_d5740c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='postlike',
            name='post_likes_post_id_c6421f_idx',
        ),
        migrations.RemoveIndex(
            model_name='postlike',
            name='post_likes_user_id_7d46ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='travelpost',
            name='travel_post_user_id_4defaa_idx',
        ),
        migrations.RemoveIndex(
            model_name='travelpost',
            name='travel_post_created_d8ddb5_idx',
        ),
        migrations.RemoveIndex(
            model_name='travelpost',
            name='travel_post_like_co_d07035_idx',
        ),
        migrations.AddField(
            model_name='plancomment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='plans.travelplan'),
        ),
        migrations.AddField(
            model_name='plancomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planlike',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='plans.travelplan'),
        ),
        migrations.AddField(
            model_name='planlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='travelpost',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='travelpost',
            name='user',
        ),
        migrations.AddIndex(
            model_name='plancomment',
            index=models.Index(fields=['plan'], name='plan_commen_plan_id_8a5913_idx'),
        ),
        migrations.AddIndex(
            model_name='plancomment',
            index=models.Index(fields=['user'], name='plan_commen_user_id_47e2a4_idx'),
        ),
        migrations.AddIndex(
            model_name='plancomment',
            index=models.Index(fields=['created_at'], name='plan_commen_created_fc5996_idx'),
        ),
        migrations.AddIndex(
            model_name='planlike',
            index=models.Index(fields=['plan'], name='plan_likes_plan_id_171347_idx'),
        ),
        migrations.AddIndex(
            model_name='planlike',
            index=models.Index(fields=['user'], name='plan_likes_user_id_3a4fc1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planlike',
            unique_together={('plan', 'user')},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
        migrations.DeleteModel(
            name='TravelPost',
        ),
    ]
