# Generated by Django 6.0 on 2025-12-30 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='현지인 칼럼 제목', max_length=200)),
                ('thumbnail_url', models.TextField(blank=True, help_text='현지인 칼럼 썸네일', null=True)),
                ('content', models.TextField(help_text='현지인 칼럼 내용 (서론)')),
                ('intro_image_url', models.TextField(blank=True, help_text='현지인 칼럼 내부 이미지', null=True)),
                ('view_count', models.IntegerField(default=0, help_text='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_columns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'local_columns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocalColumnSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='섹션 순서')),
                ('title', models.CharField(blank=True, help_text='섹션 제목', max_length=200)),
                ('content', models.TextField(help_text='섹션 내용 (설명/추천이유)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='places.localcolumn')),
            ],
            options={
                'db_table': 'local_column_sections',
                'ordering': ['column', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LocalColumnSectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(help_text='칼럼 섹션 이미지 URL')),
                ('order', models.IntegerField(default=0, help_text='이미지 순서')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.localcolumnsection')),
            ],
            options={
                'db_table': 'local_column_section_images',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('KAKAO', 'Kakao API'), ('USER', 'User Registered')], default='KAKAO', max_length=50)),
                ('place_api_id', models.CharField(blank=True, help_text='카카오맵 장소 ID', max_length=50, null=True, unique=True)),
                ('name', models.TextField(help_text='장소 이름')),
                ('category_main', models.CharField(help_text='메인 카테고리 (예: 음식점, 관광지)', max_length=50)),
                ('category_detail', models.JSONField(blank=True, default=list, help_text='상세 카테고리 리스트')),
                ('address', models.TextField(help_text='도로명 주소')),
                ('city', models.CharField(db_index=True, help_text='도시 (필터링용)', max_length=50)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('thumbnail_urls', models.JSONField(blank=True, default=list, help_text='이미지 URL 리스트', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'places',
            },
        ),
        migrations.AddField(
            model_name='localcolumnsection',
            name='place',
            field=models.ForeignKey(blank=True, help_text='섹션과 연결된 장소', null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.place'),
        ),
        migrations.AddField(
            model_name='localcolumn',
            name='representative_place',
            field=models.ForeignKey(blank=True, help_text='대표 장소 ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.place'),
        ),
        migrations.CreateModel(
            name='PlaceBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='places.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'place_bookmarks',
            },
        ),
        migrations.CreateModel(
            name='PlaceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='places.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'place_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['city'], name='places_city_3bba99_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['provider'], name='places_provide_7560e6_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['place_api_id'], name='places_place_a_84b8c1_idx'),
        ),
        migrations.AddIndex(
            model_name='placebookmark',
            index=models.Index(fields=['user'], name='place_bookm_user_id_8cc1f1_idx'),
        ),
        migrations.AddIndex(
            model_name='placebookmark',
            index=models.Index(fields=['created_at'], name='place_bookm_created_5477d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='placebookmark',
            unique_together={('user', 'place')},
        ),
    ]
