# Generated by Django 6.0 on 2025-12-30 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='현지인 칼럼 제목', max_length=200)),
                ('thumbnail_url', models.TextField(blank=True, help_text='현지인 칼럼 썸네일', null=True)),
                ('content', models.TextField(help_text='현지인 칼럼 내용 (서론)')),
                ('intro_image_url', models.TextField(blank=True, help_text='현지인 칼럼 내부 이미지', null=True)),
                ('view_count', models.IntegerField(default=0, help_text='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('representative_place', models.ForeignKey(blank=True, help_text='대표 장소 ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_columns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'local_columns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocalColumnSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='섹션 순서')),
                ('title', models.CharField(blank=True, help_text='섹션 제목', max_length=200)),
                ('content', models.TextField(help_text='섹션 내용 (설명/추천이유)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='places.localcolumn')),
                ('place', models.ForeignKey(blank=True, help_text='섹션과 연결된 장소', null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.place')),
            ],
            options={
                'db_table': 'local_column_sections',
                'ordering': ['column', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LocalColumnSectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(help_text='칼럼 섹션 이미지 URL')),
                ('order', models.IntegerField(default=0, help_text='이미지 순서')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.localcolumnsection')),
            ],
            options={
                'db_table': 'local_column_section_images',
                'ordering': ['section', 'order'],
            },
        ),
    ]
