# Generated by Django 6.0 on 2026-01-07 02:08
# Generated by Django 6.0 on 2026-01-07 01:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_localcolumn_localcolumnsection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='localcolumn',
            name='source_lang',
            field=models.CharField(default='ko', help_text='작성 언어 (예: ko, en)', max_length=10),
        ),
        migrations.AddField(
            model_name='localcolumnsection',
            name='source_lang',
            field=models.CharField(default='ko', help_text='작성 언어 (예: ko, en)', max_length=10),
        ),
        migrations.AddField(
            model_name='place',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='평균 별점 (0.00~5.00)', max_digits=3),
        ),
        migrations.AddField(
            model_name='place',
            name='review_count',
            field=models.IntegerField(default=0, help_text='리뷰 개수'),
        ),
        migrations.AddField(
            model_name='place',
            name='source_lang',
            field=models.CharField(default='ko', help_text='작성 언어 (예: ko, en)', max_length=10),
        ),
        migrations.AddField(
            model_name='placereview',
            name='source_lang',
            field=models.CharField(default='ko', help_text='작성 언어 (예: ko, en)', max_length=10),
        ),
        migrations.AlterField(
            model_name='place',
            name='category_main',
            field=models.CharField(choices=[('음식점', '음식점'), ('카페', '카페'), ('관광명소', '관광명소'), ('숙박', '숙박'), ('문화시설', '문화시설'), ('쇼핑', '쇼핑'), ('병원', '병원'), ('편의점', '편의점'), ('은행', '은행'), ('주차장', '주차장')], help_text='메인 카테고리', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='placereview',
            unique_together={('user', 'place')},
        ),
    ]
