# Generated by Django 6.0 on 2025-12-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(help_text='영상 파일 URL', max_length=500)),
                ('thumbnail_url', models.CharField(blank=True, help_text='썸네일 이미지 URL', max_length=500, null=True)),
                ('title', models.TextField(help_text='영상 제목')),
                ('content', models.TextField(blank=True, help_text='영상 설명/내용', null=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends Only'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=10)),
                ('source_lang', models.CharField(default='ko', help_text='작성 언어 (예: ko, en)', max_length=10)),
                ('total_likes', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shortforms',
            },
        ),
        migrations.CreateModel(
            name='ShortformComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source_lang', models.CharField(default='ko', max_length=10)),
                ('total_likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shortform_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortformCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shortform_comment_likes',
            },
        ),
        migrations.CreateModel(
            name='ShortformLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shortform_likes',
            },
        ),
        migrations.CreateModel(
            name='ShortformView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shortform_views',
            },
        ),
        migrations.CreateModel(
            name='TranslationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(max_length=100)),
                ('source_lang', models.CharField(help_text='원본 언어 (예: ko)', max_length=10)),
                ('target_lang', models.CharField(help_text='번역된 언어 (예: en)', max_length=10)),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('translated_text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'translation_entries',
            },
        ),
    ]
