# Generated by Django 6.0 on 2025-12-30 06:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(help_text='영상 파일 URL', max_length=255)),
                ('thumbnail_url', models.CharField(blank=True, help_text='썸네일 이미지 URL', max_length=255, null=True)),
                ('title', models.TextField(help_text='영상 제목')),
                ('content', models.TextField(blank=True, help_text='영상 설명/내용', null=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends Only'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=20)),
                ('source_lang', models.CharField(default='ko', help_text='작성 언어 (예: ko, en)', max_length=10)),
                ('total_likes', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('duration', models.IntegerField(blank=True, help_text='영상 길이 (초)', null=True)),
                ('width', models.IntegerField(blank=True, help_text='영상 너비 (px)', null=True)),
                ('height', models.IntegerField(blank=True, help_text='영상 높이 (px)', null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='파일 크기 (bytes)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortforms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shortforms',
            },
        ),
        migrations.CreateModel(
            name='ShortformComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source_lang', models.CharField(default='ko', max_length=10)),
                ('total_likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shortform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contents.shortform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shortform_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortformCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='contents.shortformcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shortform_comment_likes',
            },
        ),
        migrations.CreateModel(
            name='ShortformLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shortform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='contents.shortform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shortform_likes',
            },
        ),
        migrations.CreateModel(
            name='ShortformView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, help_text='IP 주소 (중복 체크용)', max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shortform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='contents.shortform')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shortform_views',
            },
        ),
        migrations.CreateModel(
            name='TranslationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(help_text='엔티티 타입 (shortform, comment 등)', max_length=50)),
                ('entity_id', models.BigIntegerField(blank=True, help_text='엔티티 ID')),
                ('field', models.CharField(help_text='번역할 필드명', max_length=100)),
                ('source_lang', models.CharField(help_text='원본 언어 (예: ko)', max_length=10)),
                ('target_lang', models.CharField(help_text='번역된 언어 (예: en)', max_length=10)),
                ('source_hash', models.CharField(db_index=True, help_text='SHA-256 해시', max_length=64)),
                ('translated_text', models.TextField(help_text='번역된 텍스트')),
                ('provider', models.CharField(default='nllb', help_text='번역 제공자 (nllb, google, papago 등)', max_length=50)),
                ('model', models.CharField(default='facebook/nllb-200-distilled-600M', help_text='사용된 모델명', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now, help_text='마지막 사용 시간 (캐시 정리용)')),
            ],
            options={
                'db_table': 'translation_entries',
                'indexes': [models.Index(fields=['source_hash'], name='translation_source__f9c0aa_idx'), models.Index(fields=['last_used_at'], name='translation_last_us_cf0586_idx')],
                'unique_together': {('entity_type', 'entity_id', 'field', 'target_lang')},
            },
        ),
        migrations.AddIndex(
            model_name='shortform',
            index=models.Index(fields=['user'], name='shortforms_user_id_716e76_idx'),
        ),
        migrations.AddIndex(
            model_name='shortform',
            index=models.Index(fields=['created_at'], name='shortforms_created_908a75_idx'),
        ),
        migrations.AddIndex(
            model_name='shortform',
            index=models.Index(fields=['visibility'], name='shortforms_visibil_688d2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shortformcommentlike',
            unique_together={('comment', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='shortformlike',
            unique_together={('shortform', 'user')},
        ),
        migrations.AddIndex(
            model_name='shortformview',
            index=models.Index(fields=['shortform', 'user'], name='shortform_v_shortfo_83fffd_idx'),
        ),
        migrations.AddIndex(
            model_name='shortformview',
            index=models.Index(fields=['shortform', 'ip_address'], name='shortform_v_shortfo_24b95a_idx'),
        ),
    ]
