# Generated by Django 6.0 on 2026-01-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortform',
            name='location',
            field=models.CharField(blank=True, help_text='촬영 위치 (예: Seoul, Korea)', max_length=100, null=True),
        ),
    ]
