# Generated by Django 6.0 on 2025-12-29 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shortform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortforms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shortformcomment',
            name='shortform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contents.shortform'),
        ),
        migrations.AddField(
            model_name='shortformcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shortformcommentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='contents.shortformcomment'),
        ),
        migrations.AddField(
            model_name='shortformcommentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shortformlike',
            name='shortform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='contents.shortform'),
        ),
        migrations.AddField(
            model_name='shortformlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shortformview',
            name='shortform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='contents.shortform'),
        ),
        migrations.AddField(
            model_name='shortformview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='shortform',
            index=models.Index(fields=['user'], name='shortforms_user_id_716e76_idx'),
        ),
        migrations.AddIndex(
            model_name='shortform',
            index=models.Index(fields=['created_at'], name='shortforms_created_908a75_idx'),
        ),
        migrations.AddIndex(
            model_name='shortform',
            index=models.Index(fields=['visibility'], name='shortforms_visibil_688d2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shortformcommentlike',
            unique_together={('comment', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='shortformlike',
            unique_together={('shortform', 'user')},
        ),
        migrations.AddIndex(
            model_name='shortformview',
            index=models.Index(fields=['shortform', 'user'], name='shortform_v_shortfo_83fffd_idx'),
        ),
        migrations.AddIndex(
            model_name='translationentry',
            index=models.Index(fields=['source_hash'], name='translation_source__f9c0aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='translationentry',
            unique_together={('content_type', 'object_id', 'field_name', 'target_lang')},
        ),
    ]
